# Generated by Django 4.2.3 on 2023-07-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='km',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nome',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
