# Generated by Django 4.2.3 on 2023-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_rename_image_product_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ano',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
