# Generated by Django 4.2.3 on 2023-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estado',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='km',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
    ]
